# Generated by Django 5.0.2 on 2024-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShrimpEasy', '0004_alter_farmdetails_abw_alter_farmdetails_adg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdetails',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
